export const techStack = [
  { class: "devicon-html5-plain colored", name: "HTML5" },
  { class: "devicon-css3-plain colored", name: "CSS3" },
  { class: "devicon-react-original colored", name: "React" },
  { class: "devicon-nextjs-original", name: "Next.js" },
  { class: "devicon-vuejs-plain colored", name: "Vue.js" },
  { class: "devicon-stenciljs-original colored", name: "Stencil.js" },
  { class: "devicon-typescript-plain colored", name: "TypeScript" },
  {
    class: "devicon-tailwindcss-plain colored",
    name: "Tailwind CSS",
  },
  { class: "devicon-sass-original colored", name: "SCSS / Sass" },
  { class: "devicon-nodejs-plain colored", name: "Node.js" },
  { class: "devicon-express-original colored", name: "Express.js" },
  { class: "devicon-django-plain colored", name: "Django" },
  { class: "devicon-symfony-original", name: "Symfony" },
  { class: "devicon-prisma-original colored", name: "Prisma ORM" },
  { class: "devicon-mysql-plain colored", name: "MySQL" },
  { class: "devicon-postgresql-plain colored", name: "PostgreSQL" },
  { class: "devicon-mongodb-plain colored", name: "MongoDB" },
  { class: "devicon-docker-plain colored", name: "Docker" },
  { class: "devicon-gitlab-plain colored", name: "GitLab" },
  { class: "devicon-jest-plain colored", name: "Jest" },
  { class: "devicon-cypressio-plain colored", name: "Cypress" },
  { class: "devicon-playwright-plain colored", name: "Playwright" },
];
